# Generated by Django 3.1.1 on 2020-11-02 03:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_like',
            new_name='Post_upvote',
        ),
        migrations.RenameField(
            model_name='post_upvote',
            old_name='liked_by',
            new_name='upvote_by',
        ),
    ]
