# Generated by Django 3.1.1 on 2020-11-08 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_event', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('time', models.TextField(blank=True, null=True)),
                ('pic', models.ImageField(upload_to='event_pic')),
            ],
        ),
    ]
