# Generated by Django 3.1.1 on 2020-11-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20201108_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizing_committee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
