# Generated by Django 3.1.1 on 2020-11-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20201108_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
