# Generated by Django 3.1.1 on 2020-11-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_userquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pic',
            field=models.ImageField(default='blog-post.jpg', upload_to='news_pic'),
        ),
    ]
