# Generated by Django 3.1.1 on 2020-11-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_comment_blog_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to='blog-cover'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.CharField(blank=True, choices=[('web-design', 'web-design'), ('html', 'html'), ('css', 'css'), ('freebies', 'freebies'), ('tutorials', 'tutorials')], max_length=20, null=True),
        ),
    ]
