# Generated by Django 3.1.1 on 2020-11-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201102_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Freelancer', 'Freelancer'), ('Entreprenur', 'Entreprenur'), ('Student', 'Student'), ('Professor', 'Professor')], default='student', max_length=20),
        ),
    ]
